---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: ''
  label: Pages
  create: documents
  match: "*.md"
  exclude: README.md
  new_doc_ext: ".md"
  templates:
  - blocks
- type: jekyll-pages
  label: Pages
  create: documents
  new_doc_ext: ".md"
  templates:
  - blocks
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":year:/:month:/:filename:"
instant_preview: true
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
